### ISSUE TITLE
Please use JSON::MaybeXS instead of JSON

### ISSUE THREAD

**Issue by karenetheridge** [sojiro14/JSON-MergePatch#1]
..as it supports more backends (Cpanel::JSON::XS, which is a more-maintained fork of JSON::XS).

**Comment by timbunce** [comment]
+1

**Comment by sojiro14** [comment]
Thanks for your advice. I'll try to use JSON::XS.

**Comment by sojiro14** [comment]
This module use JSON::MaybeXS from version 0.02.
https://github.com/sojiro14/JSON-MergePatch/commit/af36f93de56b3a012520e6c0c4a592c23de45d6b
